### ISSUE TITLE
no search performed.

### ISSUE THREAD

**Issue by dominix** [opto/Expression-Search-NG#1]
Hi opto,

just installed 2.4 beta in TB 78.7.1 (64 bits) 
I got the search Area (with tips text in bottom s,to,cc) bug no searchs are performed when entering any text.
Normal filter however still function.

**Comment by jaisekjames** [comment]
first restart thunderbird.
type text & hit enter or set timeout delay in option instead of 0ms.
pls check it & report a feedback.

**Comment by opto** [comment]
yes, it needs a restart. See also the installation info here:  https://github.com/opto/Expression-Search-NG/releases

**Comment by msebald** [comment]
Search does not work here, too. Also not after restart. When I put something into the search field, nothing happens. Do I need to work with expressions always now?

**Comment by opto** [comment]
which OS? Maybe see #3 for debug info

**Comment by dominix** [comment]
You're right it tooks 2 restarts of my thunderbird for the extension to works.
it is fine now, I'm happy to retrieve these functions.

**Comment by dominix** [comment]
for information, there were old variables in config from old version of expressionsearch . So I have to install, uninstall (so it cleaned up old variables), and install again. (and then restart for the magic touch)

I let you close the issue.

**Comment by msebald** [comment]
> which OS? Maybe see #3 for debug info

I run Thunderbird 78.9.0 on Windows 10. And also just tried to uninstall the old extension and the new one. Restart Thunderbird, install the new one, restart Thunderbird again. And restarted Thunderbird again.

The search field does not work anymore. As soon as I disable the new extension it is working again (after a restart of Thunderbird).

**Comment by avegaweiss** [comment]
TB 78.9.1 (64-bit) on window 10
Search don't do anything.
Already uninstalled,  and restarted several times
No error message on developer console

**Comment by opto** [comment]
I have a new version - which is restartless, as it should be - working here on TB 78.9.1. (win 10 / 64)


I will upload the new version tomorrow.

Klaus

**Comment by opto** [comment]
maybe try this: https://addons.thunderbird.net/en-us/thunderbird/addon/expression-search-ng/

**Comment by msebald** [comment]
Installed and tried briefly. Works for me now on Windows 10. Thank you! :-)
