### ISSUE TITLE
Cannot see or find expression search NG feature in Thunderbird Daily (90.x)

### ISSUE THREAD

**Issue by koobs** [opto/Expression-Search-NG#10]
Summary
----------

In the extension description I noted the following: **This extension adds a new search text box to the end of your quick search bar**, but I am unable to see, or, find a way to use, expression-search-ng in Thunderbird Daily.

I am unsure whether the extension is _intended_ to support this version, or whether the supported version declaration is incorrect, in that it declares support for versions higher than it presently actually supports.

Environment
-------------

* OS: Windows 10 Pro 20H2 19042.964 (x64)
* Thunderbird: 90.0a1 (2021-05-04) (64-bit)
* Expression-Search-NG: 2.9

Isolation Tests
---------------

 * Disable Proton
 * Restore toolbar items to default
 * Search all Menu items
 * Try entering _operators_ (is:replied) in both search fields

Screenshot
------------

![thunderbird_PefMql6O9h](https://user-images.githubusercontent.com/1011612/117093695-38b0d000-ad51-11eb-92d9-1badcfb693e5.png)

**Comment by opto** [comment]
thanks.
I didn't try/convert to TB > 78. That will follow. It may well be it is not working yet in TB 90.

Other than that, in options, you can set whether to have two search boxes or a 'unified' one.
Maybe the extension text is unclear about that, I will have a look.

Klaus

**Comment by koobs** [comment]
@opto Thank you for the response. Regarding the unified search field, I know that's an option in Firefox, but can't see a similar option available in Thunderbird?

In the meantime, I'll try removing/re-adding the extension to see if there's anything useful produced in the console for you.

Perhaps its also worth setting a max version limit (to known working versions) in the ESNG manifest so that it doesn't come up in search results for versions it doesnt (yet) work with

**Comment by koobs** [comment]
The only observable issue on addon registration (and enable event) is attached below:

![thunderbird_9FSRzKwO73](https://user-images.githubusercontent.com/1011612/117234738-15e7ef80-ae15-11eb-9adc-cb1f7fedb232.png)

**Comment by opto** [comment]
thanks. Yes, support for TB 86+ needs to come.

Klaus

**Comment by jph108** [comment]
Hello - just to add, the extension has stopped working in 91.0b5 on the Mac.

> thanks. Yes, support for TB 86+ needs to come.
> 
> Klaus

**Comment by opto** [comment]
continued in #17

**Comment by biva** [comment]
Congrats for having solved that, thank you so much!
