### ISSUE TITLE
Search bar installed, but doesn't search

### ISSUE THREAD

**Issue by zozimus1** [opto/Expression-Search-NG#2]
78.9.0 (64-bit), Mac OS 10.15.7

The add-on is installed, I restarted thunderbird. When I click on a subject it correctly put it in the search bar (e.g. simple:test) or if I type something into the box (e.g. f: David) the pop tooltip window comes up, like its going to search... but the search doesn't actually happen.

**Comment by opto** [comment]
on Win 10, that only happens directly after installation. If I then fully stop TB (and all windows for compose etc. ) and restart, the 'expression search' notice comes up in the search box and search like f:, t: or s: do work.

That is different on MacOS? Did you set any preference other than standard?

**Comment by zozimus1** [comment]
Where do you mean 'set any preference'? I don't think so. You mean in the TB preferences? I think its all standard stuff.

**Comment by opto** [comment]
see issue #3 for howto get settings

**Comment by opto** [comment]
this is now restartless. Does that work? https://addons.thunderbird.net/en-us/thunderbird/addon/expression-search-ng/
