### ISSUE TITLE
At every TB startup the tooltip window pops up empty

### ISSUE THREAD

**Issue by bege10** [opto/Expression-Search-NG#22]
Thank you very much for reviving this helpful add-on!

With TB v91.2.1 at every startup the tooltip pops up completely empty and closes after ~20 secs.
Expression-Search-NG v3.1
Windows 10 Professional 64 bit.

![Screenshot_289](https://user-images.githubusercontent.com/1184237/138632475-0f520564-4370-47ba-8f15-781ec5cee327.png)

**Comment by meichthys** [comment]
I can confirm that this is happening for me as well on v91.

**Comment by opto** [comment]
solved in 3.2, to be uploaded

**Comment by bege10** [comment]
> solved in 3.2, to be uploaded

v3.2 is still not available at addons.thunderbird.net
