### ISSUE TITLE
Add-on installed, but doesn't work after restart

### ISSUE THREAD

**Issue by zozimus1** [opto/Expression-Search-NG#3]
78.9.0 (64-bit), Mac OS 10.15.7

I installed it, restarted TB and the search bar tried to work (see my other post). But once I restart TB this function also disappears, like the add-on was never added.

Thanks for all your help fixing this essential tool!

**Comment by opto** [comment]
it seems to work on Linux and Win 10, sorry for Mac OS. I don't have any for testing.

After startup, do you see the little searchglas in the status bar? Click, goto settings, there is a checkbox for verbose information in error console.
Please restart TB, press tolls->developer tools-> error console. Any red information? 
If you do something ( a search from:name, for example), any more messages in there?

Klaus

**Comment by zozimus1** [comment]
I can now confirm that this is working perfectly! Thank you so much!!!

**Comment by opto** [comment]
thanks. And it is now accepted to addons.thunderbird.net. If you get it there, you will be in the update cycle (unless you use kaspersky, I think there is a problem)
