### ISSUE TITLE
Post-installation pops up a window that can't (easily) be closed

### ISSUE THREAD

**Issue by rootwork** [opto/Expression-Search-NG#31]
I've had Nostalgy installed for years, and recently installed three of your other addons: Expression Search NG, Quicker Quicksearch, and New Thread to All (also called New Email to All and Reply++).

In each case, after installing a window popped up with information about the plugin:

![screenshot of Expression Search NG's post-install window](https://user-images.githubusercontent.com/79733/153956016-4574400a-3bac-41cb-881d-c1781006f5fc.png)

I have no issues with you displaying this information. But this window had no easy way to close it -- the buttons at the top right (in my OS and UI) that normally close a window weren't there. Clicking outside the window didn't automatically close it, like a modal on a website. There was no "close" button at the bottom of the window. Finally I figured out that right-clicking the window I could close it that way, but that's a little ridiculous. I don't know if you're intentionally disabling the normal window chrome or if this is a bug, but please make it more straightforward to dismiss the post-install window.

I tested installing a few other addons and none of them had this issue, but I also couldn't find another addon that displays a popup window, so I'm not completely sure if this is specific to your addon's use of the popup window, or if it would affect any plugin using a popup window.

I'm running Thunderbird 91.6.0 on Linux Mint 20.3 (based on Ubuntu Focal).

This happened with all three of your addons mentioned at the top, but to reduce duplication I'm just posting it in this issue queue.

Relatedly, if you're working on this window anyway, the information contained in it was in English but linked to the German-language pages for your addons.

**Comment by opto** [comment]
It is a window created by TB, which can be closed normally in my win 11. I don't know why it cannot be closed easily in Linux.
The window is using the new webextension technology, so it may be a bug for Linux.

For most addons, I have replaced the windows by tabs, because one can leave them open with less obstruction of the working place (or close them easily).

Anyway, thanks for the info. Also for the localisation issue of the page. I will look into that as well.

Klaus

**Comment by rootwork** [comment]
Thanks for the followup -- I'll do more digging and see if it's just a Linux bug I can report to the TB team. But using a tab instead of a window in your addons (at least for the 3 I mentioned, they all opened in windows and not tabs) sounds like it'd be a good solution too.

**Comment by opto** [comment]
old bug - if still happening, please reopen. Thanks, Klaus
