### ISSUE TITLE
Incompatible with Thunderbird 98

### ISSUE THREAD

**Issue by meichthys** [opto/Expression-Search-NG#32]
![image](https://user-images.githubusercontent.com/10717998/155335940-a295c7c3-e39c-4bdc-bcb3-07f6481bf34c.png)

**Comment by opto** [comment]
it may be compatible.

To be safe, I quoted in the code. "strict_max_version": "91.*".

This makes TB > 91 refuse to install. In due time, I will look at higher TB versions for the next major release.

Klaus

**Comment by jobisoft** [comment]
Can you check out the version for Thunderbird 102?
https://github.com/opto/Expression-Search-NG/issues/41#issuecomment-1176450324

**Comment by meichthys** [comment]
I'm currently running the Thunderbird 103 beta which doesn't seem to be compatible with Expression Search, but I tested, and it works on 102👍
