### ISSUE TITLE
Tooltip can't be disable easily

### ISSUE THREAD

**Issue by quentinDupont** [opto/Expression-Search-NG#37]
Hello, and thanks a lot for the work :clap: 

I can't disable the tooltip dialog :man_shrugging: 
There's no option in the add-on menu in Thunderbird so I can't see how to do this.

It's a bit annoying as this tooltip appears each time.

I succeed to disable it thanks to this configuration item
![image](https://user-images.githubusercontent.com/9005817/165260611-a25ffa71-58a1-4365-b4e0-5899733ebb60.png)
But it's not realy user friendly :)

Thanks you

**Comment by opto** [comment]
at the moment, the options are at the blue searchglass in the status bar

**Comment by quentinDupont** [comment]
Could you add a screenshot, I can't see or I don't understand "the blue searchglass" ?

**Comment by opto** [comment]
down in the status bar (Most bottom line of TB), there is a blue icon to the very right. If you click it, there is a settings menu item.

**Comment by opto** [comment]
![image](https://user-images.githubusercontent.com/204256/165263036-c87bc733-0ad0-4793-8fde-923e40e416b9.png)

**Comment by quentinDupont** [comment]
Okeeeeeeeey ! Thank you ! 
I'm note sure that my issue is still relevant.
It's not Thunderbird user friendly but there is a solution.
