### ISSUE TITLE
[v3.4] Issue with Click2Search Setting (Ctrl+RightMouse click)

### ISSUE THREAD

**Issue by abyseedy** [opto/Expression-Search-NG#43]
Hi,

I have installed ExpressionSearchNG_3.4.zip (Thunderbird v102.0.2 on MacOS) and I have noticed that whilst the Click2Search Setting (Ctrl+RightMouse click) still works for the Date and From columns, it no longer works on the Subject column.

Could this please be fixed or am I doing something wrong?

Thanks.

**Comment by serjsk** [comment]
Have same problem with TB 102.2.0 right after TB upgrade. Tried different options (Shift, Ctrl modifier) - click2search on subject stopped working.

> I have installed ExpressionSearchNG_3.4.zip (Thunderbird v102.0.2 on MacOS) and I have noticed that whilst the Click2Search Setting (Ctrl+RightMouse click) still works for the Date and From columns, it no longer works on the Subject column.
> 
> Could this please be fixed or am I doing something wrong?

**Comment by serjsk** [comment]
When using c2s on subject error console shows:
TypeError: ExpressionSearchChrome.options.c2s_regexpMatch is undefined
[ExpressionSearchChrome.jsm:815:9](resource://expressionsearch/modules/ExpressionSearchChrome.jsm)
    RegexpReplaceString resource://expressionsearch/modules/ExpressionSearchChrome.jsm:815
    onContextMenu resource://expressionsearch/modules/ExpressionSearchChrome.jsm:852

This is Expression Search NG 3.4.2


> Have same problem with TB 102.2.0 right after TB upgrade. Tried different options (Shift, Ctrl modifier) - click2search on subject stopped working.
> 
> > I have installed ExpressionSearchNG_3.4.zip (Thunderbird v102.0.2 on MacOS) and I have noticed that whilst the Click2Search Setting (Ctrl+RightMouse click) still works for the Date and From columns, it no longer works on the Subject column.
> > Could this please be fixed or am I doing something wrong?

**Comment by opto** [comment]
workaround: quicker quicksearch addon does that. Either started by context menu of mail, or by keyboard shortcuts (not yet by mouse). email, domain or subject are earched for, but inserted nto the normal quickfilter, so you would need to display that (see options).
I will also doublecheck what is wrong here

**Comment by serjsk** [comment]
> 

Unfortunately quicker quicksearch doesn't supports regex replacement, which is the main feature I use in expression search. In my case I work a lot with ticket numbers from subject and tuned my regex to fetch ticket numbers of different formats and insert in search, thus it's not purely subject search.
I believe there is something simple broken as addon seems can't access (or parse) configuration of regex string.
I have zero experience with TB addons to debug/fix this :(

**Comment by opto** [comment]
I may have found it yesterday and can upload a testversion latest during the weekend. I also saw that all regex use seemed to be broken

**Comment by serjsk** [comment]
> I may have found it yesterday and can upload a testversion latest during the weekend. I also saw that all regex use seemed to be broken

This is great! I'm ready to test any time :)

**Comment by opto** [comment]
please test this: https://github.com/opto/Expression-Search-NG/releases/tag/v3.4.4

**Comment by serjsk** [comment]
> please test this: https://github.com/opto/Expression-Search-NG/releases/tag/v3.4.4

It works now with 3.4.4! Thank you!

**Comment by opto** [comment]
thanks for the testing

**Comment by abyseedy** [comment]
I've just installed v3.4.4 and it works perfectly!
Thank you.
