### ISSUE TITLE
Move to new window fails

### ISSUE THREAD

**Issue by pmbrandao** [opto/Expression-Search-NG#46]
Thank you very much for maintaining a very good addon.
In the recent version of Thunderbird 102 I have a problem when the addon is enabled and I try to move a tab to a new window.

Software
* windows 10
* Expression-Search-NG: 3.4.2
* Thunderbird: 102.2.0
* I have other addons, but the tests below are with only Expression-Search-NG enabled (others are disabled).
* I use the vertical view layout, but the issue occurs with classical also.
* Settings for expression search are:
 
![image](https://user-images.githubusercontent.com/9132480/187243067-578fc494-3c61-4034-beae-2ae84ffcd277.png)

Steps to reproduce:
1. In a Thunderbird main window click the calendar icon to open the calendar in a new tab
2. Right-click the calendar tab and select "move to new window"

*Expected* results:
* new window opens
* new window has the 3 pane tab with Inbox and calendar displaying

*Actual* Results
* new window opens
* only some elements are visible; there is no inbox visible; only one tab with no title (see screenshot below)

![image](https://user-images.githubusercontent.com/9132480/187243222-db77ba04-e1b5-4ff5-a46a-bb23c273cb4a.png)

Error console log with verbose information enabled
```js
TypeError: browser is null
[ext-mail.js:702:19](chrome://messenger/content/parent/ext-mail.js)
    emitDetached chrome://messenger/content/parent/ext-mail.js:702
    handleEvent chrome://messenger/content/parent/ext-mail.js:579
    closeTab chrome://messenger/content/tabmail.js:1177
    replaceTabWithWindow chrome://messenger/content/tabmail.js:1287
    <anonymous> chrome://messenger/content/tabmail.js:2081
Uncaught TypeError: domNode is null
    _bindUI chrome://messenger/content/quickFilterBar.js:257
    _init chrome://messenger/content/quickFilterBar.js:46
    onLoad chrome://messenger/content/msgMail3PaneWindow.js:561
[quickFilterBar.js:257:7](chrome://messenger/content/quickFilterBar.js)
    _bindUI chrome://messenger/content/quickFilterBar.js:257
    _init chrome://messenger/content/quickFilterBar.js:46
    onLoad chrome://messenger/content/msgMail3PaneWindow.js:561
    onLoad self-hosted:1115
```

Thank you again

**Comment by sandebert** [comment]
FWIW, I have the same situation with the main difference that I'm on TB 91.13.0.

**Comment by opto** [comment]
in my TB 102, even without expression search, the new calendar windor is empty?

**Comment by opto** [comment]
... and sometimes not ... strange.

**Comment by pmbrandao** [comment]
Problem does not occur anymore (TB 102.6.1 and Expression Search NG 3.6.3).
Do not know where the fix came from.
Thanks anyway
