### ISSUE TITLE
Warning pop up every start of TB

### ISSUE THREAD

**Issue by markusb68** [opto/Expression-Search-NG#5]
this warning pops up on every start (even after several restarts):  
![image](https://user-images.githubusercontent.com/20417704/114035603-8a178d80-987f-11eb-842d-59bd75a99f82.png)

**Comment by opto** [comment]
this is the next version. https://addons.thunderbird.net/en-us/thunderbird/addon/expression-search-ng/

Unfortunately, I forgot to take the message out. It now says the opposite, because it is now restartless.

I will take it out now for the next version.

thanks,

Klaus

**Comment by hopalongrock** [comment]
In Thunderbird 91.3.0 the warning frame completely empty!

**Comment by opto** [comment]
removed in new version, to come
