### ISSUE TITLE
TB102 not working when Expression-Search-NG is activated

### ISSUE THREAD

**Issue by LAMepelle** [opto/Expression-Search-NG#57]
Once Expression-Search-NG is installed on Thunderbird 102 for Mac (latest version) it's working as expected. After the Thunderbird window is closed (red bullet with the "x", not quit) and the window is reopened by clicking on the Thunderbird icon in the dock, the Thunderbird window is empty, i.e. emails, folders etc. are no more visible. Quitting and restarting Thunderbird fixes the problem until you close and reopen the window again. By deactivating Expression-Search-NG the problem is gone.

The error log is showing the below error when the empty window appears. The same problem seems to occur with a freshly installed Thunderbird instance and a new profile.

`10:01:20.291 Uncaught TypeError: domNode is null
    _bindUI chrome://messenger/content/quickFilterBar.js:257
    _init chrome://messenger/content/quickFilterBar.js:46
    onLoad chrome://messenger/content/msgMail3PaneWindow.js:561
quickFilterBar.js:257:7
    _bindUI chrome://messenger/content/quickFilterBar.js:257
    _init chrome://messenger/content/quickFilterBar.js:46
    onLoad chrome://messenger/content/msgMail3PaneWindow.js:561
    onLoad self-hosted:1115`

Thanks!

**Comment by LAMepelle** [comment]
Is Expression-Search-NG working for anyone with the latest Thunderbird for Mac?

**Comment by ilyasdc** [comment]
> Is Expression-Search-NG working for anyone with the latest Thunderbird for Mac?

Hi,
No, it seems to make thunderbird unable to close from time to time. But more than that, the extension stops working after some time.

**Comment by LAMepelle** [comment]
Is there an update on this? I am having the same issues with the latest version of the plugin. Thanks!

**Comment by opto** [comment]
the red X does not truely close TB, some stuff stays. What happens if go to file-> quit?

**Comment by LAMepelle** [comment]
If I quit the application it's working fine after first start. Whenever I click the red X or CMD + W, it's broken again. Error log is still pointing at similar errors.

**Comment by LAMepelle** [comment]
The latest release (https://github.com/opto/Expression-Search-NG/releases/tag/v4.0.26) has fixed the issue. Many thanks!
