### ISSUE TITLE
Options button missing

### ISSUE THREAD

**Issue by El-Pazzo** [opto/Expression-Search-NG#65]
Hi,
I can't seem to find the Options for Expression Search NG anywhere in TB. I’m using TB 102.8.0 and ES NG 3.8.10.

Best regards,
Pascal

**Comment by opto** [comment]
if the button in the status bar does not show, then the wrench in the addon manager opens the options.
Don't forget to press the save button at the bottom.

**Comment by opto** [comment]
... works in 115 (v4.0.2)
