### ISSUE TITLE
Input field missing

### ISSUE THREAD

**Issue by daniel-lo** [opto/Expression-Search-NG#73]
Hi everyone - how to I get my input field back. Currently, when I click the search icon, I get a popup window that works well but I prefer having the input field in the GUI. Anyone?

**Comment by opto** [comment]
which OS? Which TB version?

I do not quite understand the problem. The textfield for the search input/search box is always shown. In settings, you can set the position. Maybe if the position is menu bar and if the menu bar is hidden, then it is invisible. Maybe you can check there in options/settings.
Klaus

**Comment by daniel-lo** [comment]
I just have this:
![grafik](https://github.com/opto/Expression-Search-NG/assets/4311558/fd261a34-8c2a-4253-92a4-4c290b74f9da)

and if I use that button a window opens:
![grafik](https://github.com/opto/Expression-Search-NG/assets/4311558/a2807e9d-b7b0-4770-8c57-0a920b5a282b)

TB 102.12.0 (32 Bit)
Windows 11

**Comment by opto** [comment]
the (always present) search box is either in the quickfilterbar, menubar or two other positions.
Please check in extra-> addons-> wrench symbol for expression search which position is currently preset.
![image](https://github.com/opto/Expression-Search-NG/assets/204256/75ee6538-79d1-4cc6-a8d9-b0e5df932455)


you find that here:


![image](https://github.com/opto/Expression-Search-NG/assets/204256/a51d3ffd-7872-424b-b3d6-5dde44a22074)


if you have chosen quickfilterbar, is that visible, or if you have chosen menubar, is that visible? This visibility can be chosen in main Thunderbird.

Also, I propose to end the options dialog by save (at the very bottom) - maybe that resets some lost setting

**Comment by daniel-lo** [comment]
since I see the icon I guess placement is correct .. my settings
![grafik](https://github.com/opto/Expression-Search-NG/assets/4311558/f4e4dc17-2f65-4164-adca-c526a05782b9)

**Comment by opto** [comment]
so is the standard quickfilter searchfield visible?
maybe you can post a screenshot of the Thundird main window

**Comment by daniel-lo** [comment]
![grafik](https://github.com/opto/Expression-Search-NG/assets/4311558/26cd870a-0832-4a04-8518-7e47533c8cb0)

**Comment by opto** [comment]
in your case, the quickfilterbar is hidden, so you cannot see the box. What happens if you press the button Schnellfilter?

**Comment by daniel-lo** [comment]
Thanks .. that helps .. I now see a search field. Confusing to see the Expression icon (which works in a way) .. I wouldn't have thought that there are two elements.

**Comment by opto** [comment]
normally, if the quickfilterbar is visible, the searchfield is immediately visible. So it was just unfortunate circumstances
