### ISSUE TITLE
Vesrion 4 in TB115 causes Conversation tab to be blank

### ISSUE THREAD

**Issue by iokaragi** [opto/Expression-Search-NG#82]
When the plugin is enabled, the Open Message in Conversation will return a new tab that is totally blank. When the plugin is disabled, the conversation tab works normally.

Expression search and conversations are two powerful tools in message thread finding, so having to choose one or the other is creating problems.

**Comment by rhorbas** [comment]
This not only concerns conversations, the tab is blank even without this Add-On.

**Comment by quentinDupont** [comment]
Same issue here.

**Comment by ml4rrieu** [comment]
same issue here. 
TB 115.4.2
Expression Search - NG  4.0.6

**Comment by opto** [comment]
where do you find open message in conversation? Nothing in my German TB looks like that. Or is that part of the Thunderbird conversation addon?

**Comment by ml4rrieu** [comment]
here : 
![image](https://github.com/opto/Expression-Search-NG/assets/17066441/00a2343f-61ad-47ea-a9e9-b033aa6de8e9)

**Comment by opto** [comment]
please try this https://github.com/opto/Expression-Search-NG/releases/tag/v4.0.9

**Comment by ml4rrieu** [comment]
it works ! thank you !

**Comment by iokaragi** [comment]
Yes, it works like a charm now. Thank you!
