### ISSUE TITLE
Version 4 in TB 115 : Duplication of search field after disable and enable

### ISSUE THREAD

**Issue by quentinDupont** [opto/Expression-Search-NG#83]
TB v115.3.1 in Ubuntu 22.04

I had to desable, enable add-on to fix blank in conversations (see [this issue](https://github.com/opto/Expression-Search-NG/issues/82)), and the search field duplicate like this : 

![image](https://github.com/opto/Expression-Search-NG/assets/9005817/abc6edf3-ee0f-4102-aad7-3c373ca9936f)

I had to close Thunderbird to fix it.

Thanks for all the work :pray: :tada:

**Comment by opto** [comment]
https://github.com/opto/Expression-Search-NG/releases/tag/v4.0.5

**Comment by quentinDupont** [comment]
Works indeed with v4.0.5 thank youuu
