### ISSUE TITLE
Version 4 in TB 115: folder open in new tab

### ISSUE THREAD

**Issue by sunfish** [opto/Expression-Search-NG#84]
Version 4.0.0, Thunderbird 115.3.1 (64-Bit)  - Issue related with #82
When the plugin is enabled, the Open (folder) in New Tab from Folder Pane will return a new tab that is totally blank. When the plugin is disabled, the Open (folder) in New Tab works as usual.
![image](https://github.com/opto/Expression-Search-NG/assets/714627/4d78b2fc-0d4b-4ad5-8e8a-eb3ddc5bbc0d)

Expression Search NG disabled - Folder-Tab and Chat-Tab are fine
![image](https://github.com/opto/Expression-Search-NG/assets/714627/4432f61a-5d35-4079-9773-81d6eb344ede)

It would be great if this bug could be fixed

**Comment by opto** [comment]
#86 is a duplicate and has more info on this, although it was started later.
