### ISSUE TITLE
Search results after body: criteria does not refresh the result list of email 

### ISSUE THREAD

**Issue by gszathma** [opto/Expression-Search-NG#90]
After a search criteria b:  to show the results you need to change/toggle  the table view, card view buttons to refresh the results list.

**Comment by opto** [comment]
which TB, OS?

here on win 11, it is working - often. It seems some bodies cannot be searched/found, but if, then it immediately changes the view.

If you have many messages, it could take very much time, please try in a folder with only a few messages

**Comment by gszathma** [comment]
TB: 115.5.0 (64-bit) MAC OS 14.1.1. 
Testing on small folders now
Thank you, Geza
